language: ruby
rvm:
- 2.5.0
- 2.6.4
gemfile:
- gemfiles/rails_5.2.gemfile
- gemfiles/rails_6.0.gemfile
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
script:
- bundle exec rake spec
